# Site settings
title: RA Consulting | Software and Startup Consulting
email: hello@rickallen.me
description: >
  I'm a full-stack software engineer with a knack for building businesses.
  I offer startup consulting and freelance software engineering.
  I've successfully delivered more than 30 client projects ranging from startups to enterprises.
baseurl: ""
url: "http://rickallen.me"
twitter_username: stoodder
github_username: stoodder
instagram_username: stoodder

# Build settings
markdown: kramdown

gems:
 - jekyll-coffeescript