# Site settings
title: Rick Allen | Software and Startup Consulting
email: hello@rickallen.me
description: >
  WIP
baseurl: ""
url: "http://rickallen.me"
twitter_username: stoodder
github_username: stoodder
instagram_username: stoodder

# Build settings
markdown: kramdown

gems:
 - jekyll-coffeescript